Repository jupyter-server/jupyter_server_terminals, pull requests merged in 2022-04, with the labels that each got.

#2 Refactor terminals into an ExtensionApp
  .github/workflows/codeql-analysis.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  MANIFEST.in
  jupyter-config/jupyter_server_terminals.json
  jupyter_server_terminals/__init__.py
  jupyter_server_terminals/_version.py
  jupyter_server_terminals/api_handlers.py
  jupyter_server_terminals/app.py
  jupyter_server_terminals/base.py
  jupyter_server_terminals/handlers.py
  jupyter_server_terminals/terminalmanager.py
  pyproject.toml
  setup.cfg
  tests/__init__.py
  tests/conftest.py
  tests/test_terminal.py
Labels: enhancement

#8 More Cleanup
  .pre-commit-config.yaml
  docs/source/conf.py
  jupyter-config/jupyter_server_terminals.json
  jupyter_server_terminals/app.py
  jupyter_server_terminals/handlers.py
  jupyter_server_terminals/rest-api.yml
  jupyter_server_terminals/terminalmanager.py
  pyproject.toml
  setup.cfg
  tests/test_terminal.py
Labels: maintenance

#9 Automated Changelog Entry for 0.1.0 on main
  CHANGELOG.md
Labels: documentation

#11 Add authorization
  jupyter_server_terminals/api_handlers.py
  jupyter_server_terminals/app.py
  jupyter_server_terminals/handlers.py
  tests/test_auth.py
Labels: enhancement

#12 More Cleanup
  .github/workflows/test.yml
  jupyter_server_terminals/api_handlers.py
  jupyter_server_terminals/app.py
  setup.cfg
  tests/test_auth.py
  tests/test_terminal.py
Labels: enhancement

#13 Automated Changelog Entry for 0.2.0 on main
  CHANGELOG.md
Labels: documentation

#15 Fix initialize method
  jupyter_server_terminals/handlers.py
Labels: bug

#16 Automated Changelog Entry for 0.2.1 on main
  CHANGELOG.md
Labels: documentation

#18 Clean up pre-commit
  .github/workflows/test.yml
  .pre-commit-config.yaml
  CONTRIBUTING.rst
Labels: maintenance

#20 Add mypy check
  .pre-commit-config.yaml
  docs/doc-requirements.txt
  docs/source/conf.py
  jupyter_server_terminals/api_handlers.py
  jupyter_server_terminals/app.py
  pyproject.toml
  setup.py
  tests/test_auth.py
Labels: maintenance
