Repository jupyter-server/jupyter_server_terminals, pull requests merged in 2022-01, with the labels that each got.

#3 Fix links in readme
  README.md
Labels: documentation

#4 update last_activity when pty_read
  jupyter_server_terminals/terminalmanager.py
Labels: enhancement

#6 Pin pywintpy and add missing documentation page
  docs/source/contributors/contributing.rst
  docs/source/index.rst
  jupyter_server_terminals/test/test_terminal.py
  setup.cfg
Labels: bug
