Repository jupyter-server/jupyter_server_terminals, pull requests merged in 2022-09, with the labels that each got.

#42 Allow to pass string as a shell override
  jupyter_server_terminals/app.py
Labels: enhancement

#43 Automated Changelog Entry for 0.3.1 on main
  CHANGELOG.md
Labels: documentation

#45 Clean up pyproject and ci
  .github/workflows/check-release.yml
  .github/workflows/test.yml
  RELEASE.md
  pyproject.toml
Labels: maintenance
